### ISSUE TITLE
prod- og demo-deploy av fdk-statistics-service

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-statistics-service#3]
Bruker kustomize og kan i stor grad basere seg på staging-deploy

Husk:
GCP-secret "fdk-statistics-service" må opprettes for prod og demo
Database og bruker må opprettes i postgres for prod og demo

**Comment by KjerstiSteien** [comment]
@NilsOveTen Hva blokkerer denne saken?

**Comment by NilsOveTen** [comment]
> @NilsOveTen Hva blokkerer denne saken?

Må først merge det initielle apiet med staging-deploy: https://github.com/Informasjonsforvaltning/fdk-statistics-service/issues/1

Og tenker vi bør ha en versjon vi er ok med i staging før vi kjører prod-deploy, dvs minimum fikse problemet med svartid: https://github.com/Informasjonsforvaltning/fdk-statistics-service/issues/5, men kanskje også få med filtrering: https://github.com/Informasjonsforvaltning/fdk-statistics-service/issues/4

**Comment by KjerstiSteien** [comment]
Satt på vent til sakene om nevnes er løst.

**Comment by NilsOveTen** [comment]
Nå er den egentlig klar til å tas tak i, men er et par ting til jeg kan tenke meg å gjennomføre før vi prodsetter:

- [ ] Har testet en løsning for grafer basert på data fra statistics-service i staging, relevant issue her: https://github.com/Informasjonsforvaltning/fdk-portal/issues/2147
- [ ] Har kjørt et script som klarer å makse cache i fdk-statistics-service i staging, slik at vi er sikre på at den ikke har for lavt tildelt minne

**Comment by NilsOveTen** [comment]
> Har kjørt et script som klarer å makse cache i fdk-statistics-service i staging, slik at vi er sikre på at den ikke har for lavt tildelt minne

Det tar en del tid å gjennomføre requests, så har ikke testa å fylle den helt. Men er på ca 15% nå og den har ikke passert 50 MiB i høyere minnebruk. Tenker vi kan trygt kan anta at den har fått tildelt mer enn nok minne.
